# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160220_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='tob',
        ),
    ]
