# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_person_tob'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_spouse', to='blog.Person', verbose_name='Spouse'),
        ),
        migrations.AddField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Person', verbose_name='Spouse'),
        ),
    ]
